version: "3"
services:
  api:
    build: ./api
    ports:
      - "5000:5000"
      - "5001:5001"
    depends_on:
      - db
    container_name: api
  client:
    build: ./frontend
    ports:
      - "3000:3000"
    container_name: front
  db:
    image: postgres
    environment: 
      POSTGRES_USER: super
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: hypertube
    ports:
      - "5432:5432"
    container_name: psql