-- update Users set photos[2]='../img/1.jpg' where id=1;
-- SELECT u.id, u.nickName, u.dateBirth, u.photos[1], u.about FROM Users u JOIN History h ON u.id = h.idvisitor WHERE h.idvisited = (SELECT id FROM Users WHERE nickName = 'rkina');
-- INSERT INTO Connections (idFrom, idTo, status) VALUES ('4', '1', 'like');
-- SELECT u.nickName, date_part('year', age(u.dateBirth::date)) AS age, u.photos[1], u.about FROM Users u JOIN Connections c ON u.id = c.idFrom WHERE c.idTo = (SELECT id FROM Users WHERE nickName='rkina') AND status = 'like';
-- SELECT status FROM Connections WHERE idFrom = 2 AND idTo = 1;
-- SELECT status FROM Connections WHERE idFrom = (SELECT id FROM Users WHERE nickName = 'test4') AND idTo = (SELECT id FROM Users WHERE nickName = 'rkina');
-- SELECT status FROM Connections WHERE idFrom = (SELECT id FROM Users WHERE nickName = 'test4') AND idTo = (SELECT id FROM Users WHERE nickName = 'test4') OR false;
UPDATE Connections SET status = 'like' WHERE idFrom = (SELECT id FROM Users WHERE nickName = 'test4') AND idTo = (SELECT id FROM Users WHERE nickName = 'test5') RETURNING id;
INSERT INTO Connections (idFrom, idTo, status) VALUES ((SELECT id FROM Users WHERE nickName = 'test4'), (SELECT id FROM Users WHERE nickName = 'test6'), 'like');
INSERT INTO Connections (idFrom, idTo, status) VALUES ((SELECT id FROM Users WHERE nickName = 'test4'), (SELECT id FROM Users WHERE nickName = 'test7'), 'like') RETURNING id;