export const FILTER_ADD = 'FILTER_ADD';
export const FILTER_LOADING = 'FILTER_LOADING';
export const FILTER_FAILED = 'FILTER_FAILED';
export const FILTER_NICKNAME_ADD = 'FILTER_NICKNAME_ADD';
export const FILTER_PASSWORD_ADD = 'FILTER_PASSWORD_ADD';