export const NOTIFICATIONS_ADD = 'NOTIFICATIONS_ADD';
export const NOTIFICATIONS_LOADING = 'NOTIFICATIONS_LOADING';
export const NOTIFICATIONS_FAILED = 'NOTIFICATIONS_FAILED';
export const NOTIFICATIONS_PUSH = 'NOTIFICATIONS_PUSH';
