export const PROFILE_ADD = 'PROFILE_ADD';
export const PROFILE_LOADING = 'PROFILE_LOADING';
export const PROFILE_FAILED = 'PROFILE_FAILED';
export const LOGIN_ADD = 'LOGIN_ADD';
export const LOGIN_LOADING = 'LOGIN_LOADING';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOGIN_EMAIL_ADD = 'LOGIN_EMAIL_ADD';
export const LOGIN_PASSWORD_ADD = 'LOGIN_PASSWORD_ADD';